// Generated by CoffeeScript 1.8.0
(function() {
  var jade, replaceExt, through;

  jade = require('react-jade');

  through = require('through2');

  replaceExt = require('replace-ext');

  module.exports = function(opt) {
    var stream;
    stream = through.obj(function(file, enc, callback) {
      var templateString;
      if (file.isNull()) {
        this.push(file);
        return callback();
      } else if (file.isBuffer()) {
        templateString = jade.compileClient(file.contents.toString(), opt).toString();
        file.contents = new Buffer('module.exports = ' + templateString);
        file.path = replaceExt(file.path, '.js');
        this.push(file);
        return callback();
      } else if (file.isStream()) {
        throw new Error('Streams are not supported');
      }
      return callback();
    });
    return stream;
  };

}).call(this);
